services:
  webapp-frontend:
    build:
      context: ./Webapp
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    env_file:
      - ./.env
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - NODE_ENV=development
    volumes:
      - ./Webapp:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build:
      context: ./Webapp
      dockerfile: backend.Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./Webapp/.env
    volumes:
      - ./Webapp:/app
    command: ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "3001"]
    working_dir: /app
    restart: unless-stopped
