services:
  webapp:
    build:
      context: ./Webapp
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    env_file:
      - ./.env
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - NODE_ENV=development
    volumes:
      - ./Webapp:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
